### 查询服务
GET http://127.0.0.1:9001/edcode/scacommerce-nacos-client/nacos-client/service-instance?serviceId=sca-commerce-gateway
Accept: application/json
sca-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJzY2EtY29tbWVyY2UtdXNlciI6IntcImlkXCI6MTEsXCJ1c2VybmFtZVwiOlwiZWRkaWVAcXEuY29tXCJ9IiwianRpIjoiNjg0ZWRkZmQtNWZmMC00OTJlLWI1M2ItYTlmY2MzZDQzYmU3IiwiZXhwIjoxNjQxNjU3NjAwfQ.eRCnSn9eKPyMN8O1Sky5jGizdnv96xtuo8evOHKwytIrz6aYBAyrGuAnTdDIG7EOdU0wPUom-uU52sPaLAVw0LPbfefGrbKqsuVIsNG2IOiwkwl_fqLm6IxSC8jDEFTTCNH6-01WJ2gKZ2LrRn_ZGizQ3w0Y30KL6mK2vpx31Nb6kf_fospqL1iW7VoQQWgiY9tBQ790M4fMT9IcpEzWD6-w0j4_9nWlArEotrHMb5_FCBzqRBx6v0rQQcNwa667zFfZqn2UOw25Ajz859DmTagvjxPaFVJNwF3udsIIxLGQalE8E3-lDrqAoR-29Apf5uHINHSezqEY6PCmBP8tXg
token: edcode ## HeaderTokenGatewayFilter

###
