### 查询服务
GET http://127.0.0.1:9001/edcode/scacommerce-nacos-client/nacos-client/service-instance?serviceId=sca-commerce-gateway
Accept: application/json
sca-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJzY2EtY29tbWVyY2UtdXNlciI6IntcImlkXCI6MTEsXCJ1c2VybmFtZVwiOlwiZWRkaWVAcXEuY29tXCJ9IiwianRpIjoiMWU1MGI2ZWYtNmUzOS00YmY2LWJlMjktZDc4NWU3NWQyNmY1IiwiZXhwIjoxNjM1OTU1MjAwfQ.P7GxZuMUrgiMUbD4dNYzQiV3A6YkaFpvlzg8cpBdu_hvxqDsVEuuiYODQSzZPQeN3xTQPbJ70zkSY084HV7Vsk929en1lqNiX_dpQEuGSbz2JSPqyJuLZ6v7hRX9GI32sPrZAnaKVXMdeHUXCMMmaS1L3osimSvAlaoDE0n2UukDLgu83xRlL3bddHIJbmFD5BrV6Y-u9d-blqXPOpxFEYkdwS_XrljYiULTH7Olr71TAwODUPdttnmVhHPXB0_dnOG5DZMOC0OxqokHGZJ7CC86paE4TvdNPwqotB6u6zh_d_YCCBWM3t1LmKYB6E_bnz2taL5Q4AYHlRaZZotaAA
token: edcode ## HeaderTokenGatewayFilter

###
