### 登录
POST 127.0.0.1:9001/edcode/sca-commerce/login
Content-Type: application/json

{
  "username": "eddie@qq.com",
  "password": "25d55ad283aa400af464c76d713c07ad"
}


### 根据 TableId 查询详细商品信息
POST http://127.0.0.1:9001/edcode/scacommerce-goods-service/goods/goods-info
Content-Type: application/json
sca-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJzY2EtY29tbWVyY2UtdXNlciI6IntcImlkXCI6MTEsXCJ1c2VybmFtZVwiOlwiZWRkaWVAcXEuY29tXCJ9IiwianRpIjoiYTdhMjU4OTUtZmRjYi00ZWQ3LTg2MDEtZGMzZmY5Y2FlMDg4IiwiZXhwIjoxNjM3MTY0ODAwfQ.ihMZ14UdfTPMPyln8zOyP-_pM3X-VySZF6b0YKkbLmgEGbqc6zVS8E1NxqQ_XfSIaqbCb0a6GQnviBi1tEEwZL7U7Yyq4SsvuA4iGWpz2bgd-DS0qyCFvCxMeH6Q6yphYmej4IGF7EJ_EGIa0RfSuySa_tXrcKK6Xv5B0x4kkuWu57E61j3e1q1gqq_Ozn8NuB-iTzvxcepjczmLLkcuMqJ8EDHMd8j54CzUCbHb8it_2bZ6DnOc7pP2aZBxl7HaE7eo-LoaO_4QECuX2PcvGEe34hjTkT6_ahRBiWZZqxb15wjkTfP-rwHwFuCqHx0Ysou_4l766PxXVkP35lQlpQ

{
  "ids": [
    {
      "id": 1
    },
    {
      "id": 2
    }
  ]
}


### 根据分页查询简单商品信息
GET http://127.0.0.1:9001/edcode/scacommerce-goods-service/goods/page-simple-goods-info?page=1
Accept: application/json
sca-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJzY2EtY29tbWVyY2UtdXNlciI6IntcImlkXCI6MTEsXCJ1c2VybmFtZVwiOlwiZWRkaWVAcXEuY29tXCJ9IiwianRpIjoiYTdhMjU4OTUtZmRjYi00ZWQ3LTg2MDEtZGMzZmY5Y2FlMDg4IiwiZXhwIjoxNjM3MTY0ODAwfQ.ihMZ14UdfTPMPyln8zOyP-_pM3X-VySZF6b0YKkbLmgEGbqc6zVS8E1NxqQ_XfSIaqbCb0a6GQnviBi1tEEwZL7U7Yyq4SsvuA4iGWpz2bgd-DS0qyCFvCxMeH6Q6yphYmej4IGF7EJ_EGIa0RfSuySa_tXrcKK6Xv5B0x4kkuWu57E61j3e1q1gqq_Ozn8NuB-iTzvxcepjczmLLkcuMqJ8EDHMd8j54CzUCbHb8it_2bZ6DnOc7pP2aZBxl7HaE7eo-LoaO_4QECuX2PcvGEe34hjTkT6_ahRBiWZZqxb15wjkTfP-rwHwFuCqHx0Ysou_4l766PxXVkP35lQlpQ


### 根据 TableId 查询简单商品信息: 完整的 goods cache
### 第二步验证, 删掉 cache
### 第三步验证, 删除 cache 中其中一个商品
POST http://127.0.0.1:9001/edcode/scacommerce-goods-service/goods/simple-goods-info
Content-Type: application/json
sca-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJzY2EtY29tbWVyY2UtdXNlciI6IntcImlkXCI6MTEsXCJ1c2VybmFtZVwiOlwiZWRkaWVAcXEuY29tXCJ9IiwianRpIjoiYTdhMjU4OTUtZmRjYi00ZWQ3LTg2MDEtZGMzZmY5Y2FlMDg4IiwiZXhwIjoxNjM3MTY0ODAwfQ.ihMZ14UdfTPMPyln8zOyP-_pM3X-VySZF6b0YKkbLmgEGbqc6zVS8E1NxqQ_XfSIaqbCb0a6GQnviBi1tEEwZL7U7Yyq4SsvuA4iGWpz2bgd-DS0qyCFvCxMeH6Q6yphYmej4IGF7EJ_EGIa0RfSuySa_tXrcKK6Xv5B0x4kkuWu57E61j3e1q1gqq_Ozn8NuB-iTzvxcepjczmLLkcuMqJ8EDHMd8j54CzUCbHb8it_2bZ6DnOc7pP2aZBxl7HaE7eo-LoaO_4QECuX2PcvGEe34hjTkT6_ahRBiWZZqxb15wjkTfP-rwHwFuCqHx0Ysou_4l766PxXVkP35lQlpQ

{
  "ids": [
    {
      "id": 1
    },
    {
      "id": 2
    }
  ]
}


### 扣减商品库存
PUT http://127.0.0.1:9001/edcode/scacommerce-goods-service/goods/deduct-goods-inventory
Content-Type: application/json
sca-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJzY2EtY29tbWVyY2UtdXNlciI6IntcImlkXCI6MTEsXCJ1c2VybmFtZVwiOlwiZWRkaWVAcXEuY29tXCJ9IiwianRpIjoiYTdhMjU4OTUtZmRjYi00ZWQ3LTg2MDEtZGMzZmY5Y2FlMDg4IiwiZXhwIjoxNjM3MTY0ODAwfQ.ihMZ14UdfTPMPyln8zOyP-_pM3X-VySZF6b0YKkbLmgEGbqc6zVS8E1NxqQ_XfSIaqbCb0a6GQnviBi1tEEwZL7U7Yyq4SsvuA4iGWpz2bgd-DS0qyCFvCxMeH6Q6yphYmej4IGF7EJ_EGIa0RfSuySa_tXrcKK6Xv5B0x4kkuWu57E61j3e1q1gqq_Ozn8NuB-iTzvxcepjczmLLkcuMqJ8EDHMd8j54CzUCbHb8it_2bZ6DnOc7pP2aZBxl7HaE7eo-LoaO_4QECuX2PcvGEe34hjTkT6_ahRBiWZZqxb15wjkTfP-rwHwFuCqHx0Ysou_4l766PxXVkP35lQlpQ

[
  {
    "goodsId": 1,
    "count": 100
  },
  {
    "goodsId": 2,
    "count": 34
  }
]

###
