### 获取 Token
POST http://127.0.0.1:9001/edcode/scacommerce-nacos-client/communication/token-by-feign
Content-Type: application/json
sca-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJzY2EtY29tbWVyY2UtdXNlciI6IntcImlkXCI6MTEsXCJ1c2VybmFtZVwiOlwiZWRkaWVAcXEuY29tXCJ9IiwianRpIjoiNjYzNWMzNzctNzU1OC00YTE3LTgwZDgtZGRkNjMwNDRlOWY3IiwiZXhwIjoxNjM5NDExMjAwfQ.YCuXyNFXSJBRQQPEYAn_k--IgsVcwG1yrkPIfEdPyaO3cs4gs4JhDiNSHtAOnI6Jm0-eedO6GZ9a0B85lT5mN6B1Oko9SYsIb5qPUvFHD3rcAlJoOF7uRqf6QSVismBCS-xY5ewiVRRHvfsEZ-Kksa9yOsHD5OfpuSMtSHZhXsRKUA-MZjfrhwMDfx6Vg-BfVbnvAJVK2vbxyzq2-rSnFeYrfd38QK6hmO_PJrB83Xht8CU8RTari0uys4GsudZnLciAV1pxRbx5Lpg95008ltezX9-AuamEsbnq0of7OwY8TfOlhcpMBYWLR8rE7Fda8djCFLSvblrpqFniT1480A
token: edcode

{
  "username": "eddie@qq.com",
  "password": "25d55ad283aa400af464c76d713c07ad"
}


### 根据提供的 serviceId 获取实例信息
GET http://127.0.0.1:9001/edcode/scacommerce-nacos-client/hystrix/hystrix-command-annotation?serviceId=e-commerce-nacos-client
Content-Type: application/json
sca-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJzY2EtY29tbWVyY2UtdXNlciI6IntcImlkXCI6MTEsXCJ1c2VybmFtZVwiOlwiZWRkaWVAcXEuY29tXCJ9IiwianRpIjoiNjYzNWMzNzctNzU1OC00YTE3LTgwZDgtZGRkNjMwNDRlOWY3IiwiZXhwIjoxNjM5NDExMjAwfQ.YCuXyNFXSJBRQQPEYAn_k--IgsVcwG1yrkPIfEdPyaO3cs4gs4JhDiNSHtAOnI6Jm0-eedO6GZ9a0B85lT5mN6B1Oko9SYsIb5qPUvFHD3rcAlJoOF7uRqf6QSVismBCS-xY5ewiVRRHvfsEZ-Kksa9yOsHD5OfpuSMtSHZhXsRKUA-MZjfrhwMDfx6Vg-BfVbnvAJVK2vbxyzq2-rSnFeYrfd38QK6hmO_PJrB83Xht8CU8RTari0uys4GsudZnLciAV1pxRbx5Lpg95008ltezX9-AuamEsbnq0of7OwY8TfOlhcpMBYWLR8rE7Fda8djCFLSvblrpqFniT1480A
token: edcode


### 根据提供的 serviceId 获取实例信息
GET http://127.0.0.1:9001/edcode/scacommerce-nacos-client/hystrix/simple-hystrix-command?serviceId=e-commerce-nacos-client
Content-Type: application/json
sca-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJzY2EtY29tbWVyY2UtdXNlciI6IntcImlkXCI6MTEsXCJ1c2VybmFtZVwiOlwiZWRkaWVAcXEuY29tXCJ9IiwianRpIjoiNjYzNWMzNzctNzU1OC00YTE3LTgwZDgtZGRkNjMwNDRlOWY3IiwiZXhwIjoxNjM5NDExMjAwfQ.YCuXyNFXSJBRQQPEYAn_k--IgsVcwG1yrkPIfEdPyaO3cs4gs4JhDiNSHtAOnI6Jm0-eedO6GZ9a0B85lT5mN6B1Oko9SYsIb5qPUvFHD3rcAlJoOF7uRqf6QSVismBCS-xY5ewiVRRHvfsEZ-Kksa9yOsHD5OfpuSMtSHZhXsRKUA-MZjfrhwMDfx6Vg-BfVbnvAJVK2vbxyzq2-rSnFeYrfd38QK6hmO_PJrB83Xht8CU8RTari0uys4GsudZnLciAV1pxRbx5Lpg95008ltezX9-AuamEsbnq0of7OwY8TfOlhcpMBYWLR8rE7Fda8djCFLSvblrpqFniT1480A
token: edcode


### 根据提供的 serviceId 获取实例信息
GET http://127.0.0.1:9001/edcode/scacommerce-nacos-client/hystrix/hystrix-observable-command?serviceId=e-commerce-nacos-client
Content-Type: application/json
sca-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJzY2EtY29tbWVyY2UtdXNlciI6IntcImlkXCI6MTEsXCJ1c2VybmFtZVwiOlwiZWRkaWVAcXEuY29tXCJ9IiwianRpIjoiNjYzNWMzNzctNzU1OC00YTE3LTgwZDgtZGRkNjMwNDRlOWY3IiwiZXhwIjoxNjM5NDExMjAwfQ.YCuXyNFXSJBRQQPEYAn_k--IgsVcwG1yrkPIfEdPyaO3cs4gs4JhDiNSHtAOnI6Jm0-eedO6GZ9a0B85lT5mN6B1Oko9SYsIb5qPUvFHD3rcAlJoOF7uRqf6QSVismBCS-xY5ewiVRRHvfsEZ-Kksa9yOsHD5OfpuSMtSHZhXsRKUA-MZjfrhwMDfx6Vg-BfVbnvAJVK2vbxyzq2-rSnFeYrfd38QK6hmO_PJrB83Xht8CU8RTari0uys4GsudZnLciAV1pxRbx5Lpg95008ltezX9-AuamEsbnq0of7OwY8TfOlhcpMBYWLR8rE7Fda8djCFLSvblrpqFniT1480A
token: edcode

###
